Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/WordArray:
    Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
